### ISSUE TITLE
Small optimisations, encapsulation, loose coupling and cleanup

### ISSUE THREAD

**Issue by deepansh96** [avantifellows/plio-frontend#102]
**Describe the task**
The current frontend code was not utilising the full power Vue provides. This PR #103 solves some of those issues. 
Some of the tasks are outlined below with their explanation and reference links (if any).

- [x] Encapsulate axios API calls into separate service files. Attaching a quote from the vuemastery course,
> If we’re importing Axios into each component that needs it, we’re unnecessarily creating a new instance of Axios each time we do that. With API code woven throughout our application, this gets messy and makes our app harder to debug. A cleaner and more scalable solution is to modularize our API code into a service layer.
- [x] Router links had a tight coupling with the path of the component that it is linking to. This tight coupling is not scalable. If in future, any of our routing path changes, the router link will need to be edited.
- [x] Also, another instance of tight coupling is how params and queries are passed through the router to different components. Instead of accessing them like `this.$route.params.id`, the `id` param should be passed as a prop to the component.
- [x] The loading spinner is added to individual components and is tightly coupled with that component itself. But we also need a loading spinner that works globally across the app.
- [x] While importing files into components and other files, the file paths look like `../../bla_bla.vue`. Using `@/bla_bla.vue` is a better solution. `@` here means `src/`
- [x] Throughout the code, the Vuex store states are being accessed through store getters, which is not required. Store getters should be used if we need a derived state/computed state.
- [x] Utilizing helper functions like `mapState`, `mapActions`, `mapGetters` throughout the code. This significantly reduces the code. Instead of writing `this.$store.dispatch('action-name')`, using a `mapActions` would reduce that line to `this.action-name()`
- [x] In a vuex store module `"plioItems"`, namespacing has to be added.

**Comment by pritamps** [comment]
Excellent!!!
