### ISSUE TITLE
Add country code to user login

### ISSUE THREAD

**Issue by dalmia** [avantifellows/plio-frontend#67]
Add a box for country code in the login page

**Comment by pritamps** [comment]
I was thinking: why this? The students don't seem to have a problem with it, no?

**Comment by deepansh96** [comment]
@dalmia we decided to not do this right? If yes, then let's close the issue

**Comment by dalmia** [comment]
Yes, although we are not adding now - we'll probably do it in the future. Isliye, did not tie it to any milestone. We'll close an issue only if something turns out to not be an issue or something we won't ever do!

**Comment by pritamps** [comment]
I would agree with @deepansh96  and close it off. 

When we add it, it won't be "Add Country Code to User Login", but instead it will be something like "Support Users from USA" or "Enable OTP for non-Indian numbers" or something like that. This task is too specific to be saved the axe :D

**Comment by dalmia** [comment]
Agreed!
