### ISSUE TITLE
Remove country code hardcoding

### ISSUE THREAD

**Issue by dalmia** [avantifellows/plio-frontend#68]
91 is hardcoded in a few places

Linked to:
https://github.com/avantifellows/plio-backend/issues/42
https://github.com/avantifellows/db-queries/issues/39
https://github.com/avantifellows/plio-dashboard/issues/29

**Comment by dalmia** [comment]
I have a doubt - I need to remove hardcoding from everywhere of `91` prepended to user-id. For that, we'll have to change say the user ID from `7003060871` to `917003060871` everywhere, including the response name and response json.
This will break production right? Should we put plio on maintenance or something for some time while we do these changes?
We'll have to rename all the S3 files and while that is happening and while the PR (when I make one) is open, there will be inconsistencies and things will break, no?
For example, when I make the PR - for it to work correctly, the renaming would have to be done already but if the renaming has been done but the code is not deployed yet - things will break on production, no?

@pritamps @deepansh96

**Comment by pritamps** [comment]
1. Please find the exact bug
2. Find exact repro steps

And then we can see about fixing it. We need to know exactly what we are fixing before taking down production. Hardocding 91 is not a problem in itself (yet) because all our students are in India as of now

**Comment by dalmia** [comment]
There is no hardcoding in this repo really. Closing it.
