### ISSUE TITLE
Vue not able to recognise MathJax object sometimes

### ISSUE THREAD

**Issue by deepansh96** [avantifellows/plio-frontend#82]
**Describe the bug**
The user sees a compilation error thrown when the project is served. This error can be seen either on vue ui or by serving through the command line. This error is seen while serving locally or while deploying for staging or production.

The compilation error is as follows
```
error  'MathJax' is not defined  no-undef
```

`MathJax` JS files are being injected into the document by an external CDN link. Information from the link is fetched, added to the DOM. But until then, there is actually no `MathJax` object defined according to vue, hence the error.

**To Reproduce**
Note: This bug cannot be reproduced 100% of the time. Sometimes it appears sometimes it doesn't.
1. Serve the project locally (either using Vue ui or through vue cli)
2. As the project compiles, it will throw the error
3. The error goes away while re-compiling

**Expected behavior**
The user should not see the compilation error, the project should compile properly

**Screenshots**
<img width="1151" alt="Screenshot 2021-03-11 at 4 47 49 PM" src="https://user-images.githubusercontent.com/20169829/110779428-85b08280-8289-11eb-82e4-ee5cd8da68aa.png">

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.1
 - Browser: Brave Browser
 - Version: Chromium: 88.0.4324.152

**Additional context**
Somehow, sometimes Vue is able to fetch mathjax scripts from the CDN and then it knows that `MathJax` object is defined but sometimes it's not able to do that

Also, compiling the project for the first time doesn't give this error but hot reloading always gives this error

**Comment by pritamps** [comment]
https://stackoverflow.com/questions/36210062/vue-is-not-defined 

Maybe try this? Use "text/javascript" instead of "javascript" in the tag?

**Comment by deepansh96** [comment]
> https://stackoverflow.com/questions/36210062/vue-is-not-defined
> 
> Maybe try this? Use "text/javascript" instead of "javascript" in the tag?

Tried, didn't work

**Comment by pritamps** [comment]
This is only while compiling no? Or students see this also?

**Comment by deepansh96** [comment]
Only while compiling.
Sometimes it compiles perfectly, sometimes it doesn't.
Have to recompile once or twice to make the error go away.

Once it's compiled and deployed, the error does not appear anywhere - students don't see this

**Comment by TJ-coding** [comment]
On a different project. I replaced the `MathJax` references in the Vue.js code to `window.MathJax` and it fixed the issue. I'm not sure if it will work here.
