### ISSUE TITLE
Error when trying to update locale if logged out

### ISSUE THREAD

**Issue by dalmia** [avantifellows/plio-frontend#87]
**Describe the bug**
Every time someone switches the locale, the code updates  the local and remote user config. However, there is no user config when the user is logged out. Currently, it still tries to update them which gives an error.

**Comment by pritamps** [comment]
Yeah.. this is what I meant in the previous PR when I said that logic/code of updating locale should be separate from the logic/code of updating the users config :)

**Comment by pritamps** [comment]
Saw in PR that it was fixed 👍🏾
